version: "3.8"

services:
  identity:
    image: identity_api
    build:
      context: ./src/weylo.identity/
      dockerfile: app.Dockerfile
    container_name: identity_api
    environment:
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - postgres
    ports:
      - 5000:80
    networks:
      - myappnetwork
    restart: always
  postgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Pass1234!
      POSTGRES_DB: weylo
    volumes:
    - mypostgresdb_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - myappnetwork
    restart: always

networks:
  myappnetwork:
    driver: bridge

volumes:
  mypostgresdb_data: