version: "3.8"

services:
  identity:
    image: identity_api
    build:
      context: .
      dockerfile: identity.Dockerfile
    container_name: identity_api
    environment:
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 5000:80
    networks:
      - myappnetwork
    restart: always

  user:
    build:
      context: .
      dockerfile: user.Dockerfile  
    container_name: user_api 
    ports:
      - "5001:81"
    environment:
      - ASPNETCORE_URLS=http://+:81  
    depends_on:
      - postgres 
      - identity  
    networks:
      - myappnetwork 
    env_file:
      - .env  
    restart: always
  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile  
    container_name: admin_api 
    ports:
      - "5002:82"
    environment:
      - ASPNETCORE_URLS=http://+:82 
    depends_on:
      - postgres 
      - identity  
    networks:
      - myappnetwork 
    env_file:
      - .env  
    restart: always

  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    container_name: gateway_api
    ports:
      - "4000:83"
    environment:
      - ASPNETCORE_URLS=http://+:83
    depends_on:
      - identity
      - user
    networks:
      - myappnetwork
    restart: always


  postgres:
    image: postgres:latest
    container_name: mypostgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - mypostgresdb_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5433:5432"
    networks:
      - myappnetwork
    restart: always

networks:
  myappnetwork:
    driver: bridge

volumes:
  mypostgresdb_data: