version: "3.8"

services:
  identity:
    image: identity_api
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: identity_api
    environment:
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 5000:80
    networks:
      - myappnetwork
    restart: always
  postgres:
    image: postgres:latest
    container_name: mypostgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - mypostgresdb_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5433:5432"
    networks:
      - myappnetwork
    restart: always

networks:
  myappnetwork:
    driver: bridge

volumes:
  mypostgresdb_data: